export interface AmcItem {
  name: string
  logo: string
  scale?: number
}

export const ALL_AMCS: AmcItem[] = [
  { name: '360 ONE Mutual Fund', logo: '/amc-logos/360-one.webp', scale: 1.3 },
  { name: 'Abakkus Mutual Fund', logo: '/amc-logos/abakkus.webp', scale: 1.1 },
  { name: 'Aditya Birla Sun Life Mutual Fund', logo: '/amc-logos/aditya-birla.webp' },
  { name: 'AlphaGrep Mutual Fund', logo: '/amc-logos/alphagrep.webp', scale: 1.1 },
  { name: 'ASK Mutual Fund', logo: '/amc-logos/ask.webp', scale: 1.1 },
  { name: 'Axis Mutual Fund', logo: '/amc-logos/axis.webp', scale: 1.15 },
  { name: 'Bajaj Finserv Mutual Fund', logo: '/amc-logos/bajaj-finserv.webp', scale: 1.1 },
  { name: 'Bandhan Mutual Fund', logo: '/amc-logos/bandhan.webp', scale: 1.1 },
  { name: 'Bank of India Mutual Fund', logo: '/amc-logos/bank-of-india.webp' },
  { name: 'Baroda BNP Paribas Mutual Fund', logo: '/amc-logos/baroda-bnp-paribas.webp', scale: 1.4 },
  { name: 'Canara Robeco Mutual Fund', logo: '/amc-logos/canara-robeco.webp', scale: 1.2 },
  { name: 'Capitalmind Mutual Fund', logo: '/amc-logos/capitalmind.webp', scale: 1.1 },
  { name: 'Choice Mutual Fund', logo: '/amc-logos/choice.webp', scale: 1.1 },
  { name: 'DSP Mutual Fund', logo: '/amc-logos/dsp.webp', scale: 1.15 },
  { name: 'Edelweiss Mutual Fund', logo: '/amc-logos/edelweiss.webp' },
  { name: 'Franklin Templeton Mutual Fund', logo: '/amc-logos/franklin-templeton.webp', scale: 1.3 },
  { name: 'Groww Mutual Fund', logo: '/amc-logos/groww.webp', scale: 1.2 },
  { name: 'HDFC Mutual Fund', logo: '/amc-logos/hdfc.webp', scale: 1.1 },
  { name: 'Helios Mutual Fund', logo: '/amc-logos/helios.webp', scale: 1.1 },
  { name: 'HSBC Mutual Fund', logo: '/amc-logos/hsbc.webp', scale: 1.1 },
  { name: 'ICICI Prudential Mutual Fund', logo: '/amc-logos/icici-prudential.webp' },
  { name: 'IL&FS Mutual Fund (IDF)', logo: '/amc-logos/ilfs.webp', scale: 1.15 },
  { name: 'Invesco Mutual Fund', logo: '/amc-logos/invesco.webp', scale: 1.1 },
  { name: 'ITI Mutual Fund', logo: '/amc-logos/iti.webp' },
  { name: 'JM Financial Mutual Fund', logo: '/amc-logos/jm-financial.webp', scale: 1.3 },
  { name: 'Kotak Mahindra Mutual Fund', logo: '/amc-logos/kotak.webp', scale: 1.1 },
  { name: 'LIC Mutual Fund', logo: '/amc-logos/lic.webp', scale: 1.3 },
  { name: 'Mahindra Manulife Mutual Fund', logo: '/amc-logos/mahindra-manulife.webp', scale: 1.1 },
  { name: 'Mirae Asset Mutual Fund', logo: '/amc-logos/mirae-asset.webp' },
  { name: 'Motilal Oswal Mutual Fund', logo: '/amc-logos/motilal-oswal.webp' },
  { name: 'Navi Mutual Fund', logo: '/amc-logos/navi.webp', scale: 1.1 },
  { name: 'Nippon India Mutual Fund', logo: '/amc-logos/nippon-india.webp' },
  { name: 'PGIM India Mutual Fund', logo: '/amc-logos/pgim-india.webp', scale: 1.1 },
  { name: 'PPFAS Mutual Fund', logo: '/amc-logos/ppfas.webp', scale: 1.3 },
  { name: 'Quant Mutual Fund', logo: '/amc-logos/quant.webp', scale: 1.2 },
  { name: 'Quantum Mutual Fund', logo: '/amc-logos/quantum.webp', scale: 1.25 },
  { name: 'Samco Mutual Fund', logo: '/amc-logos/samco.webp' },
  { name: 'SBI Mutual Fund', logo: '/amc-logos/sbi.webp', scale: 1.35 },
  { name: 'Shriram Mutual Fund', logo: '/amc-logos/shriram.webp', scale: 1.2 },
  { name: 'Sundaram Mutual Fund', logo: '/amc-logos/sundaram.webp', scale: 1.3 },
  { name: 'Tata Mutual Fund', logo: '/amc-logos/tata.webp', scale: 1.25 },
  { name: 'Trust Mutual Fund', logo: '/amc-logos/trust.webp', scale: 1.15 },
  { name: 'Union Mutual Fund', logo: '/amc-logos/union.webp' },
  { name: 'UTI Mutual Fund', logo: '/amc-logos/uti.webp', scale: 1.35 },
  { name: 'WhiteOak Capital Mutual Fund', logo: '/amc-logos/whiteoak.webp', scale: 1.2 },
  { name: 'The Wealth Company Mutual Fund', logo: '/amc-logos/wealth-company.webp', scale: 1.15 },
]
