export interface AmcItem {
  name: string
  logo: string
  scale?: number
}

export const ALL_AMCS: AmcItem[] = [
  { name: '360 ONE Mutual Fund', logo: '/amc-logos/360-one.svg' },
  { name: 'Abakkus Mutual Fund', logo: '/amc-logos/abakkus.svg', scale: 1.1 },
  { name: 'Aditya Birla Sun Life Mutual Fund', logo: '/amc-logos/aditya-birla.svg' },
  { name: 'AlphaGrep Mutual Fund', logo: '/amc-logos/alphagrep.svg', scale: 1.1 },
  { name: 'ASK Mutual Fund', logo: '/amc-logos/ask.svg', scale: 1.1 },
  { name: 'Axis Mutual Fund', logo: '/amc-logos/axis.svg', scale: 1.05 },
  { name: 'Bajaj Finserv Mutual Fund', logo: '/amc-logos/bajaj-finserv.svg', scale: 1.1 },
  { name: 'Bandhan Mutual Fund', logo: '/amc-logos/bandhan.svg', scale: 1.1 },
  { name: 'Bank of India Mutual Fund', logo: '/amc-logos/bank-of-india.svg' },
  { name: 'Baroda BNP Paribas Mutual Fund', logo: '/amc-logos/baroda-bnp-paribas.svg', scale: 1.1 },
  { name: 'Canara Robeco Mutual Fund', logo: '/amc-logos/canara-robeco.svg', scale: 1.1 },
  { name: 'Capitalmind Mutual Fund', logo: '/amc-logos/capitalmind.svg', scale: 1.1 },
  { name: 'Choice Mutual Fund', logo: '/amc-logos/choice.svg', scale: 1.1 },
  { name: 'DSP Mutual Fund', logo: '/amc-logos/dsp.svg', scale: 1.1 },
  { name: 'Edelweiss Mutual Fund', logo: '/amc-logos/edelweiss.svg' },
  { name: 'Franklin Templeton Mutual Fund', logo: '/amc-logos/franklin-templeton.svg', scale: 1.15 },
  { name: 'Groww Mutual Fund', logo: '/amc-logos/groww.svg' },
  { name: 'HDFC Mutual Fund', logo: '/amc-logos/hdfc.svg', scale: 1.05 },
  { name: 'Helios Mutual Fund', logo: '/amc-logos/helios.svg', scale: 1.1 },
  { name: 'HSBC Mutual Fund', logo: '/amc-logos/hsbc.svg', scale: 1.1 },
  { name: 'ICICI Prudential Mutual Fund', logo: '/amc-logos/icici-prudential.svg' },
  { name: 'IL&FS Mutual Fund (IDF)', logo: '/amc-logos/ilfs.svg', scale: 1.15 },
  { name: 'Invesco Mutual Fund', logo: '/amc-logos/invesco.svg', scale: 1.1 },
  { name: 'ITI Mutual Fund', logo: '/amc-logos/iti.svg' },
  { name: 'JM Financial Mutual Fund', logo: '/amc-logos/jm-financial.svg', scale: 1.1 },
  { name: 'Kotak Mahindra Mutual Fund', logo: '/amc-logos/kotak.svg', scale: 1.1 },
  { name: 'LIC Mutual Fund', logo: '/amc-logos/lic.svg' },
  { name: 'Mahindra Manulife Mutual Fund', logo: '/amc-logos/mahindra-manulife.svg', scale: 1.1 },
  { name: 'Mirae Asset Mutual Fund', logo: '/amc-logos/mirae-asset.svg' },
  { name: 'Motilal Oswal Mutual Fund', logo: '/amc-logos/motilal-oswal.svg' },
  { name: 'Navi Mutual Fund', logo: '/amc-logos/navi.svg', scale: 1.1 },
  { name: 'Nippon India Mutual Fund', logo: '/amc-logos/nippon-india.svg' },
  { name: 'PGIM India Mutual Fund', logo: '/amc-logos/pgim-india.svg', scale: 1.1 },
  { name: 'PPFAS Mutual Fund', logo: '/amc-logos/ppfas.svg' },
  { name: 'Quant Mutual Fund', logo: '/amc-logos/quant.svg', scale: 1.05 },
  { name: 'Quantum Mutual Fund', logo: '/amc-logos/quantum.svg', scale: 1.05 },
  { name: 'Samco Mutual Fund', logo: '/amc-logos/samco.svg' },
  { name: 'SBI Mutual Fund', logo: '/amc-logos/sbi.svg', scale: 1.1 },
  { name: 'Shriram Mutual Fund', logo: '/amc-logos/shriram.svg', scale: 1.05 },
  { name: 'Sundaram Mutual Fund', logo: '/amc-logos/sundaram.svg' },
  { name: 'Tata Mutual Fund', logo: '/amc-logos/tata.svg' },
  { name: 'Trust Mutual Fund', logo: '/amc-logos/trust.svg', scale: 1.15 },
  { name: 'Union Mutual Fund', logo: '/amc-logos/union.svg' },
  { name: 'UTI Mutual Fund', logo: '/amc-logos/uti.svg' },
  { name: 'WhiteOak Capital Mutual Fund', logo: '/amc-logos/whiteoak.svg', scale: 1.1 },
  { name: 'The Wealth Company Mutual Fund', logo: '/amc-logos/wealth-company.svg', scale: 1.15 },
]
