export interface AmcItem {
  name: string
  logo: string
  scale?: number
}

export const ALL_AMCS: AmcItem[] = [
  { name: '360 ONE Mutual Fund', logo: '/amc-logos/360-one.png' },
  { name: 'Abakkus Mutual Fund', logo: '/amc-logos/abakkus.png', scale: 1.1 },
  { name: 'Aditya Birla Sun Life Mutual Fund', logo: '/amc-logos/aditya-birla.png' },
  { name: 'AlphaGrep Mutual Fund', logo: '/amc-logos/alphagrep.png', scale: 1.1 },
  { name: 'ASK Mutual Fund', logo: '/amc-logos/ask.svg', scale: 1.1 },
  { name: 'Axis Mutual Fund', logo: '/amc-logos/axis.png', scale: 1.05 },
  { name: 'Bajaj Finserv Mutual Fund', logo: '/amc-logos/bajaj-finserv.png', scale: 1.1 },
  { name: 'Bandhan Mutual Fund', logo: '/amc-logos/bandhan.png', scale: 1.1 },
  { name: 'Bank of India Mutual Fund', logo: '/amc-logos/bank-of-india.png' },
  { name: 'Baroda BNP Paribas Mutual Fund', logo: '/amc-logos/baroda-bnp-paribas.png', scale: 1.1 },
  { name: 'Canara Robeco Mutual Fund', logo: '/amc-logos/canara-robeco.png', scale: 1.1 },
  { name: 'Capitalmind Mutual Fund', logo: '/amc-logos/capitalmind.png', scale: 1.1 },
  { name: 'Choice Mutual Fund', logo: '/amc-logos/choice.png', scale: 1.1 },
  { name: 'DSP Mutual Fund', logo: '/amc-logos/dsp.png', scale: 1.1 },
  { name: 'Edelweiss Mutual Fund', logo: '/amc-logos/edelweiss.png' },
  { name: 'Franklin Templeton Mutual Fund', logo: '/amc-logos/franklin-templeton.png', scale: 1.15 },
  { name: 'Groww Mutual Fund', logo: '/amc-logos/groww.png' },
  { name: 'HDFC Mutual Fund', logo: '/amc-logos/hdfc.png', scale: 1.05 },
  { name: 'Helios Mutual Fund', logo: '/amc-logos/helios.png', scale: 1.1 },
  { name: 'HSBC Mutual Fund', logo: '/amc-logos/hsbc.png', scale: 1.1 },
  { name: 'ICICI Prudential Mutual Fund', logo: '/amc-logos/icici-prudential.png' },
  { name: 'IL&FS Mutual Fund (IDF)', logo: '/amc-logos/ilfs.svg', scale: 1.15 },
  { name: 'Invesco Mutual Fund', logo: '/amc-logos/invesco.png', scale: 1.1 },
  { name: 'ITI Mutual Fund', logo: '/amc-logos/iti.png' },
  { name: 'JM Financial Mutual Fund', logo: '/amc-logos/jm-financial.png', scale: 1.1 },
  { name: 'Kotak Mahindra Mutual Fund', logo: '/amc-logos/kotak.png', scale: 1.1 },
  { name: 'LIC Mutual Fund', logo: '/amc-logos/lic.png' },
  { name: 'Mahindra Manulife Mutual Fund', logo: '/amc-logos/mahindra-manulife.png', scale: 1.1 },
  { name: 'Mirae Asset Mutual Fund', logo: '/amc-logos/mirae-asset.png' },
  { name: 'Motilal Oswal Mutual Fund', logo: '/amc-logos/motilal-oswal.png' },
  { name: 'Navi Mutual Fund', logo: '/amc-logos/navi.png', scale: 1.1 },
  { name: 'Nippon India Mutual Fund', logo: '/amc-logos/nippon-india.png' },
  { name: 'PGIM India Mutual Fund', logo: '/amc-logos/pgim-india.png', scale: 1.1 },
  { name: 'PPFAS Mutual Fund', logo: '/amc-logos/ppfas.png' },
  { name: 'Quant Mutual Fund', logo: '/amc-logos/quant.png', scale: 1.05 },
  { name: 'Quantum Mutual Fund', logo: '/amc-logos/quantum.png', scale: 1.05 },
  { name: 'Samco Mutual Fund', logo: '/amc-logos/samco.png' },
  { name: 'SBI Mutual Fund', logo: '/amc-logos/sbi.png', scale: 1.1 },
  { name: 'Shriram Mutual Fund', logo: '/amc-logos/shriram.png', scale: 1.05 },
  { name: 'Sundaram Mutual Fund', logo: '/amc-logos/sundaram.png' },
  { name: 'Tata Mutual Fund', logo: '/amc-logos/tata.png' },
  { name: 'Trust Mutual Fund', logo: '/amc-logos/trust.png', scale: 1.15 },
  { name: 'Union Mutual Fund', logo: '/amc-logos/union.png' },
  { name: 'UTI Mutual Fund', logo: '/amc-logos/uti.png' },
  { name: 'WhiteOak Capital Mutual Fund', logo: '/amc-logos/whiteoak.png', scale: 1.1 },
  { name: 'The Wealth Company Mutual Fund', logo: '/amc-logos/wealth-company.svg', scale: 1.15 },
]
